config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'welcome#index'

  get 'up' => 'rails/health#show', as: :rails_health_check

  get 'manifest'       => 'rails/pwa#manifest', as: :pwa_manifest
  get 'service-worker' => 'rails/pwa#service_worker', as: :pwa_service_worker

  get 'welcome/index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= content_for(:title) || 'Rubedo'
    %meta{ content: 'text/html; charset=UTF-8', 'http-equiv' => 'Content-Type' }/
    %meta{ content: 'width=device-width,initial-scale=1', name: 'viewport' }/
    %meta{ content: 'yes', name: 'apple-mobile-web-app-capable' }/
    %meta{ content: 'yes', name: 'mobile-web-app-capable' }/
    = csrf_meta_tags
    = csp_meta_tag
    = yield :head
    = tag.link rel: 'manifest', href: pwa_manifest_path(format: :json)
    %link{ href: '/icon.png', rel: 'icon', type: 'image/png' }/
    %link{ href: '/icon.svg', rel: 'icon', type: 'image/svg+xml' }/
    %link{ href: '/icon.png', rel: 'apple-touch-icon' }/
    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', type: 'module', defer: true
  %body
    = yield

app/views/welcome/index.html.haml
%h1 Welcome#index
%p Find me in app/views/welcome/index.html.haml